### ISSUE TITLE
Gatsby compatibility

### ISSUE THREAD

**Issue by ohlr** [elbywan/yett#29] opened 2020-08-17 18:14 UTC
using React Helmet the script gets added below scripts injected through plugins such as google analytics, which makes it unusable.

I guess to make this work we would need a gatsby-yett plugin

**Comment by elbywan** [comment] 2020-08-18 06:13
Hi @ohlr,

Could you elaborate a bit on this and provide reproducible code to demonstrate why `yett` would be incompatible with gatsby?

**Comment by ohlr** [comment] 2020-08-18 09:54
My Assumption:
There are plugins for analytics such as https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/ they inject their sripts before React Helmet https://github.com/nfl/react-helmet thus yett cannot disable them.

**Comment by elbywan** [comment] 2020-08-18 18:32
Thanks for clarifying!

> There are plugins for analytics such as https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/ they inject their sripts before React Helmet https://github.com/nfl/react-helmet thus yett(injected through helmet) cannot disable them.

I'm not familiar enough with Gatsby but indeed this sounds like a script ordering issue between the `google-analytics` and `react-helmet` plugins. I'm wondering if Gatsby provides other means of modifying the `<head>` contents, while browsing the docs I saw that you could [customize html.js](https://www.gatsbyjs.com/docs/custom-html/). Maybe that it could be relevant?

> I guess to make this work we would need a gatsby-yett plugin

In the meantime, I'm going to close the issue since this is not a problem that concerns `yett` directly and cannot be solved here.

**Closed by elbywan** 2020-08-18 18:32 UTC
Labels: question
